### ISSUE TITLE
proposal for a uribeacon flag

### ISSUE THREAD

**Issue by tolson2000** [google/uribeacon#130]
I don't know what "hidden" flag in the uribeacon really is for. But I have an issue with physical web that I think can be resolved with such a flag. Or perhaps this is what that "hidden" flag is for.

It has to do with the "Edit URL's" feature that every user sees on their smart device's physical web tool. Assume 1000 bored passengers waiting in an Aiport terminal. Many of whom will experiment with the feature and try to select and change found Uri Beacons.

The casual millions of users will never have a need for the feature and should not be confused by having the feature presented to them. Perhaps the feature should only appear once a beacon as been manually (at the beacon) reset into the programming mode.

**Comment by dinhviethoa** [comment]
Our suggestion of implementation is to have a physical trigger to enable the Edit URL feature on the device.
- It can be a button that enables the edit mode for 10 seconds
- Or it can be a reset button and the device URL can only be edited when the URL is blank

**Comment by tolson2000** [comment]
Yes, I agree, a physical trigger on the beacon device is essential to drop it into Edit mode. What I am suggesting is to then set a bit in the advertizement flags to let a physcial web or other app know the beacon is in the updatable mode. I feel that the app should not have a Edit URL function exposed until there is a beacon willing to be re-programmed. Then a connection and authentication procedure can commence. The millions of people have no need to even know there is a Edit URL function available on the phone until they own a beacon.

**Comment by dinhviethoa** [comment]
Oh I see. Thanks for the feedback.

**Comment by scottjenson** [comment]
The 'hidden' flag is intended for devices that broadcast a URL but are
controlled by a master device. Imagine a room of lightbulbs but there is
one one master lighting system. You don't want all of those lightbulbs
showing up in your list when they clearly don't need to be. The "hidden"
flag is there to the client to optionally hide that item from the user. Of
course, it could, for example  group all hidden items under a hidden folder
if it really wanted to.

We've discovered that nearly anything can be done with meta data on the web
page that the URL points to but having a flag like hidden makes it much
much easier that making the full round trip each time.

Scott

**Comment by tolson2000** [comment]
Thanks Scott for explaining that hidden flag. What do you think about the idea of not having the "Edit URL" menu item showing up on millions of phones that have no business knowing about editing beacons. I think that feature can normally never show up in a users phone except when there really is a uribeacon preparing to be modified. I think to make that work, we need a flag for that purpose.

**Comment by scottjenson** [comment]
The "Edit URL" is entirely a utility function for makers using this first
round. Once we have this in a mainstream form, it will no longer be
offered. That ability will be put off to the URI Beacon app (or something
that the manufacturer ships with their beacons. In fact, in the longer run,
we expect most beacons to be configured at the factory and not be editable
at all. So in other words, this will change drastically as this product
space matures.

Scott

**Comment by tolson2000** [comment]
OK, that sounds perfect then. Thanks a bunch.
