### ISSUE TITLE
Where is protocol specification for updating URI OTA

### ISSUE THREAD

**Issue by tolson2000** [google/uribeacon#135]
Not sure if this is the right place. The physical web app mentions uploading URL to beacons from the smart devices. It seems they refer to V1 and V2 beacons. Where is the specification protocol that is expected to be in the beacon to make this possible?

**Comment by g-ortuno** [comment]
When you say "uploading URL to beacons from smart devices" do you mean: changing the URI that the beacon is broadcasting using a cellphone/tablet?

**Comment by tolson2000** [comment]
Yes, I'm looking for the protocol specification to change the URI of the beacon using a cellphone/tablet.
I know we don't intend for that feature to exist for the billions. But for now since it in for testing, I'd like to give a go at allowing my beacons to be changed via whatever protocol that is. Thanks.

**Comment by schilit** [comment]
Here it is:
https://github.com/google/uribeacon/blob/master/specification/ConfigService.md

Bill

**Comment by g-ortuno** [comment]
It's worth pointing out that right now the beacons that we are using have a button and when the button is pressed the beacon begins broadcasting the Config Service so it can be configured. Hope it helps!
