### ISSUE TITLE
Issues Detecting Arduino Beacon

### ISSUE THREAD

**Issue by chriswhitcombe** [google/uribeacon#151]
I've just setup a red bear labs blend micro as a beacon, everything looks fine and boots accordingly with feedback in the serial monitor. However when I try to detect the beacon nothing shows up.

My first thought was this was down to software on my phone (iPhone) but when I try on an android it still fails. I then swapped the software on the blend micro to the BLEPeripheral simple chat example, all worked fine.

That leads me to think the blend micro is working and it cant be the phone (as many phones all fail) so there must be something I'm missing with the setup of the software.

The pin outs are correct for the blend micro (6, 7, 4) and the beacon appears to be advertising itself when i use a generic bluetooth scanner to find it (pictures attached).

Does anyone have any idea why the scanner finds it but the physical web application cant? I'm out of ideas as to how I can further debug this?

![img_5278](https://cloud.githubusercontent.com/assets/1093637/5835461/d6c8295e-a160-11e4-9e04-d442d5d8ef19.PNG)
![img_5279](https://cloud.githubusercontent.com/assets/1093637/5835460/d6c396dc-a160-11e4-82eb-de59e2fb0e07.PNG)

**Comment by schilit** [comment]
Are you broadcasting according to the specification for UriBeacon
<https://github.com/google/uribeacon/tree/master/specification#uribeacon-advertising-data>
?

AdvDataLocalName is not in the spec.

Bill

**Comment by chriswhitcombe** [comment]
The code I'm using is just the standard demo code

```
// Import libraries (BLEPeripheral depends on SPI)
#include <SPI.h>
#include <BLEPeripheral.h>
#include <URIBeacon.h>

// define pins (varies per shield/board)
//
//   Adafruit Bluefruit LE   10, 2, 9
//   Blend                    9, 8, UNUSED
//   Blend Micro              6, 7, 4
//   RBL BLE Shield           9, 8, UNUSED

#define URI_BEACON_REQ   6
#define URI_BEACON_RDY   7
#define URI_BEACON_RST   4

URIBeacon uriBeacon(URI_BEACON_REQ, URI_BEACON_RDY, URI_BEACON_RST);

void setup() {
  Serial.begin(9600);

#if defined (__AVR_ATmega32U4__)
  //Wait until the serial port is available (useful only for the Leonardo)
  //As the Leonardo board is not reseted every time you open the Serial Monitor
  while(!Serial) {
  }
  delay(5000);  //5 seconds delay for enabling to see the start up comments on the serial board
#endif

  uriBeacon.begin(0x00, 0x20, "http://www.e.com"); // flags, power, URI

  Serial.println(F("URI Beacon"));
}

void loop() {
  uriBeacon.loop();
}
```

After running another arduino program onto it with a null advertising data, then running the example again I manage to get rid of that field.

Looking at what is left the Service Data reads:

FED8 = <00200165 07>

In terms of the code the 00 and 20 make sense as the flags and power
The 01 maps to https://www. 
The 65 maps to e
And the 07 maps to .com

From my perspective that appears to meet the needs to the specification and is built using the BLEPeripheral code sample.

Im wondering if the UUID may be wrong but since its only used in scanning I wonder why that would impact the functioning of the physical web application.

**Comment by schilit** [comment]
Take a look at the ADV packet using Nordic's nRF Master Control Panel on
Android.

This app parses UriBeacon packets. Tap the scan item to expand. Then see if
it is showing 0xFED8 or whether it is incorrectly byte swapped as 0xD8FE.

**Comment by sandeepmistry** [comment]
@chriswhitcombe just tested this with my Blend Micro getting the same behaviour with iOS.

However, if I re-enabled connectivity, it works, remove the following line: https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/master/URIBeacon.cpp#L44

@schilit not sure why the scanner would behave differently when flags are set to non-connectable.

**Comment by chriswhitcombe** [comment]
@sandeepmistry that one liner does fix the problem. Haven't had a chance to pull the iOS code yet but will try and grab it asap to try and understand more why it failed.

**Comment by sandeepmistry** [comment]
On the Android side, nRF Master Control panel detects the URI beacon without the change I suggested above. Physical Web on Android also does not list the beacon without the change.

**Comment by g-ortuno** [comment]
@dinhviethoa Any ideas?

**Comment by dinhviethoa** [comment]
Hi @sandeepmistry and @chriswhitcombe,
You're missing the following field in the advertising data:
```
    kCBAdvDataServiceUUIDs =     (
        FED8
    );
```
It should let the beacon appear on iOS.
See "UriBeacon Advertising Data", offset 1 and 2.
It will allow detection of beacons in a battery efficient way.

**Comment by sandeepmistry** [comment]
@dinhviethoa thanks for looking into this.

I must not have a correct bit set in [arduino-BLEPeripheral](https://github.com/sandeepmistry/arduino-BLEPeripheral) when in connectable mode on nRF8001. I'll look into this over the next fews days, and post an update here.

**Comment by sandeepmistry** [comment]
@chriswhitcombe please try with the latest master version of [arduino-BLEPeripheral](https://github.com/sandeepmistry/arduino-BLEPeripheral).

I pushed an change to address the service uuid not being advertised when in non-connectable (broadcast) mode. No changes are needed for the Arduino example in this repo.

**Comment by schilit** [comment]
Sounds like this is resolved. Closing.
