### ISSUE TITLE
Products support for iBlio - valterforesto

### ISSUE THREAD

**Issue by valterforesto** [google/uribeacon#171]
At www.iblio.net we have implemented the URI Beacon GATT characteristics tree using specifications for configuring a Bluetooth Low Energy module BEACON and using the Configuration Service described on https://github.com/google/uribeacon/blob/master/specification/ConfigService.md.
I'm using the last Physical Web app version 0.1.830 on an Android 4.4.2 Samsung Galaxy S4 to discover and attempt configuration of my BEACONs during the tests.
I'm not actually able to enter the "Edit URLs" configurations mode from the Physical Web app also when the Lock State characteristic of my module BEACON is 'unlocked' (0).

So, my question is: how a Physical Web app locate beacons in an unlooked state when "Edit URLs" is entered on the app ?

Thanks, Valter.

**Comment by g-ortuno** [comment]
Hi Valter,
Thanks for your interest in the Physical Web. If you are working on your own implementation of the UriBeacon I would recommend you use the [UriBeacon Sample App](https://github.com/google/uribeacon/releases). The UriBeacon Sample App will allow you to configure each of the characteristics describe in the Config Service document.

**Comment by scottjenson** [comment]
I'd also suggest that you post any URIBeacon specific issues on the URIBeacon github:
https://github.com/google/uribeacon
That repo covers the beacons, we cover the scanning agent (but of course, we work closely together)

As we've giving you a gentle push in the right direction, I'm going to close this issue then... Please reopen if you have any follow up questions.

**Comment by scottjenson** [comment]
Silly me, I clearly go between the two repos too quickly. Sorry, reopened as you are exactly where you should be...

**Comment by schilit** [comment]
If you are not seeing the beacon when you enter "Edit URLs" then verify the ADV packet you have for UriBeacon Config as it is different than the ADV packet for UriBeacon. See beacons/mbed/main.cpp for an example.

**Comment by valterforesto** [comment]
Hi g-ortuno,
I downloaded the APK of UriBeacon Validation App "uribeacon-validator-release.apk" into the Android 4.4.2 Samsung Galaxy S4 but it cannot be installed (packed analysis error).
No problem instead downloading, installing an running "uribeacon-sample-release.apk".

**Comment by corymast** [comment]
I ran into the same problem installing the validator app on my Samsung Galaxy S4 running Android 4.4.2. The app can only be installed on devices running Android 5.0 "Lollipop" because I believe the project uses vectored icons which Isn't supported in Android 4.4.2. Try installing on an android device running Android "L" and see if that solves the problem.

**Comment by valterforesto** [comment]
Hi schilit,
where I can read official informations / specifications about the two mentioned different GAP packets used during Advertisement and during Config Scan Response ?
( I'm currently developing URI Beacon firmware using BGScript on a Bluegiga BLE112 module, I have look also at uribeacon/beacons/BLE113 but the example only advertise and configuration is not implemented) .

**Comment by schilit** [comment]
Hi!

We are in review on a BLE112 implementation in BGScript. Take a look at Pull
Request 116 <https://github.com/google/uribeacon/pull/166>. Comments
welcome.

The UriBeacon ADV packet is defined in UriBeacon Advertising Data
<https://github.com/google/uribeacon/tree/master/specification#uribeacon-advertising-data>
in
the spec and a reference is in mbed implementation startAdvertisingUriBeacon
<https://github.com/google/uribeacon/blob/master/beacons/mbed/main.cpp#L151>
.

The UriBeacon Config ADV packet is not well documented. It has: Name,
16-Byte UUIDs, TX Power. A reference is in the mbed implementation in
startAdvertisingUriBeaconConfig
<https://github.com/google/uribeacon/blob/master/beacons/mbed/main.cpp#L106>
.

Hope this helps!

Bill

**Comment by valterforesto** [comment]
The message popup "Put UriBeacon in Config Mode" in the Physical Web and UriBeacon apps mean that some human phisical  action must be taken on the beacon hardware to enable Configuration ?

**Comment by schilit** [comment]
The preferred use case is for an administrator to put the device in config
mode, either by power cycling the beacon or pressing a (hidden) button.

This allows the beacon to exit configuration mode. If the beacon were
connectable all the time then that creates a denial of service attack
potential: people can come along and make a GATT connection which stops
beaconing.

That said we do have situations where the beacons are in a controlled
environment but are not physically accessible and those beacons are
configured to be connectable all the time.

Bill

**Comment by valterforesto** [comment]
@schilit Hi Bill and @roywant Roy,

I have reviewed and tested yours suggested BLE112 implementation in BGScript at Pull
Request 116 <https://github.com/google/uribeacon/pull/166> that works fine.

Valter

**Comment by valterforesto** [comment]
I'm starting, a pre-productions of iBLIO UriBeacons focused on selling Physical Web beacons based on our implementations using the Bluegiga BLED112, BLE112, BLE113 and BLE121LR and just tested with Physical Web and UriBeacon standard and validation apps.

**Comment by schilit** [comment]
Great news. Do you have a general web site and one with your products we can eventually cross-link to?

**Comment by androidcodecn** [comment]
I am from China, I am doing the same work on selling Physical Web beacons.

**Comment by valterforesto** [comment]
@schilit Hi Bill,

at www.iblio.net we are starting selling BEACONs KITs of ours "iBlio UriBeacon dongle USB" and "iBlio UriBeacon Boxed".
All iBlio beacons passed the current UriBeacon valitation tests.

The "iBlio UriBeacon dongle USB" can be powered from its USB port using a USB power-bank or USB power-supply.
The "iBlio UriBeacon Boxed" is powered using CR2032 button-battery that can be replaced unscrewing two screws.
On April 2015 we start also selling two new type of UriBeacon, a sealed and a long-range Iblio UriBeacon.

As you can see on our web-site www.iblio.net we are focused on Bluetooth Low Energy BEACONS, SENSORS and ACTUATORS in many forms.
We are also working hard to facilitate use of Smartphones and Tablets for the physical interactions with sensors and actuators based on our Bluetooth Low Energy solutions that does not require special Apps Developers skills. 
We believe that the open-source Physical Web and UriBeacon approach of Google will soon open a great path for smart things, like sensors and actuators combined in many way, to reach the Internet and facilitate human physical interactions with new innovative products.

**Comment by schilit** [comment]
@androidcodecn moved to another issue, please follow up there.
@valterforesto renamed this issue to "Product support for..."

**Comment by valterforesto** [comment]
I am a iBlio CTO, so I changed the title of this issue because the UriBeacon support is targeted to iBlio beacons.

**Comment by valterforesto** [comment]
@g-ortuno @schilit
When is the expected release of the new version 1.3 of UriBeacon Valitation App for Android L?

**Comment by g-ortuno** [comment]
The new version is in the final stages of development. If no breaking bugs
are found it should be up by tomorrow night.

**Comment by g-ortuno** [comment]
@valterforesto The new version of the Validation App is now available. 

https://github.com/google/uribeacon/releases/tag/v1.3

**Comment by valterforesto** [comment]
@g-ortuno Thanks Giovanni,
we will redo the all validation tests on our beacons products using the new UriBeacon Validation App v1.3 to assess our implementation of UriBeacon for the Physical Web on all Bluegiga modules and USB-dongle we are using expecially for our new long-range beacon based on BLE121LR.

**Comment by valterforesto** [comment]
Validation tests passed on our www.iblio.net UriBeacon products using the new UriBeacon Validation App v1.3 to (re)assess our firmware implementation on Bluegiga modules BLE112, BLED112 dongle and our new long-range beacon based on BLE121LR.

**Comment by schilit** [comment]
Excellent news! 

I added iBLio to the README.md file.

Let me know if I can close this tracking issue.

**Comment by valterforesto** [comment]
@schilit 
You can close this tracking issue since all our UriBeacon products passed the new UriBeacon Validation App v1.3 Tests. Thanks.
