### ISSUE TITLE
Product support for androidcodecn

### ISSUE THREAD

**Issue by schilit** [google/uribeacon#173]
@androidcodecn Let's use this issue to track support questions.

Please add to this issue: the web site URL for your product, the hardware platform, and any questions you have.

You should look at the Validation App and Configuration Appl (sample) under [release](https://github.com/google/uribeacon/release) and the [reference implementations](https://github.com/google/uribeacon/blob/master/beacons/README.md).

**Comment by androidcodecn** [comment]
My web site is http://wifibeacon.cn.   Now I'm using TI CC2541 to make a Uribeacon. I'm very interested in Physical Web. But in China,there are a few people konw this technology.So I want to build a chinese website about Physical Web. What do you think of this idea?

**Comment by schilit** [comment]
Please make sure to link to uribeacon.org and physical-web.org.

Bill

**Comment by androidcodecn** [comment]
Yeah,I'am sure

**Comment by schilit** [comment]
This looks great. Do you have any other issues you'd like us to help with?
