### ISSUE TITLE
To Implement the UriBeacon on LilyPad-nano51822

### ISSUE THREAD

**Issue by ucxpresso** [google/uribeacon#186]
We have implemented the UriBeacon on our LilyPad-nano51822. 
The Lilypad-nano51822 are working with the "Tickless" technology  and the power consumption are avg. 26uA with a LED blink. 

UriBeacon V2 source code for 51822: 
https://github.com/ucxpresso/nano51822/tree/master/examples/cookbook/ble_uri_beacon_v2

Note:
The code provides a button to easy to change the mode (Normal and Configure) without reset.

Getting Started for developer:
http://www.embeda.com.tw/ucxpresso/?article=getting-started-2

Purchase the kit:
http://www.amazon.com/uCXpresso-LilyPad-nano51822-Arduino-iBeacon/dp/B00RE6CL4G/ref=sr_1_1?s=pc&ie=UTF8&qid=1423637775&sr=1-1

Our Web Site:
http://www.ucxpresso.net

**Comment by scottjenson** [comment]
This is great news! Have you run the validator app to confirm your implementation? 
https://github.com/google/uribeacon/releases (uribeacon-validator-release.apk)

**Comment by schilit** [comment]
Nice!

When it passes the validation it would be great if you could issue a pull
request to add links to
https://github.com/google/uribeacon/blob/master/beacons/README.md

thanks,

Bill

**Comment by ucxpresso** [comment]
The code is the UriBeacon V1 now.
We will implement and open the UriBeacon V2 code for the validator. 

One question, 
I can not install the "uribeacon-validator-release.apk" on the Android 4.4.x. Is it for the Android 5.x only ?

**Comment by g-ortuno** [comment]
Yes. The validator app is only available in android 5.0

**Comment by ucxpresso** [comment]
Sorry, I don't have the Android 5.0 now, so I can not try the validator...

We have port the V2 source code for 51822 on the GitHub:
https://github.com/ucxpresso/nano51822/tree/master/examples/cookbook/ble_uri_beacon_v2

And try with UriBeacon App to configure the beacon:
1. Save without "Lock" , work well.
2. Save with "Lock", and enter UriBeacon Password "1234", then I got the result "Failed with code: 0x0d".

What is the password format? or something wrong?

**Comment by g-ortuno** [comment]
Sorry could you clarify the steps you took? What values did you try to write? 0x0d means Invalid Attribute Length.

**Comment by ucxpresso** [comment]
Step1. Enable the "Lock" and Click the "SAVE TO BEACON"
Step2. Enter the UriBeacon Password: 1234, and click the "Write".
Step3. Failed with code: 13

The screenshot: 
https://www.dropbox.com/sh/ejzok93u0t8olu4/AACh6fVryEnx_5_IudwF3xFQa?dl=0

**Comment by g-ortuno** [comment]
Hmm. For some reason the beacon is returning invalid length. When you enter '1234' the sample app converts it to a 128bit array which is then send to the beacon. So maybe your implementation is not handling the length correctly.

**Comment by ucxpresso** [comment]
Hi g-ortuno,

Yes, you are right.
The key length is incorrect, and it work well for "Lock" now.

Thanks

**Comment by j796160836** [comment]
We made it !
We have pass the test.

**Comment by ucxpresso** [comment]
(I am looking for Android 5.0 device in long time)
Yes, We ran the "validator app" and passed.
and Open Source in our web sit:
http://www.embeda.com.tw/ucxpresso/?article=2-3-google-uribeacon-project

thanks

**Comment by g-ortuno** [comment]
Congrats! One thing: I noticed you are using the Blesh Physical Web app,
could you use the Official Physical Web App in your site? Here is the link
to it:

https://play.google.com/store/apps/details?id=physical_web.org.physicalweb

**Comment by ucxpresso** [comment]
OK, 
But I am changed to use the "UriBeacon-Sample" apk for the "Advanced Settings", and I need to highlight the V2 nice features.

**Comment by g-ortuno** [comment]
Great! Thanks a lot!

**Comment by scottjenson** [comment]
BTW, I've added the LilyPad link to the Physical Web github home page as well.

**Comment by ucxpresso** [comment]
Dear g-ortuno and scottjenson,
Thank for your supported. 
We hope, we can help the UriBeacon project with our source code.
