### ISSUE TITLE
Product Page with images, etc

### ISSUE THREAD

**Issue by schilit** [google/uribeacon#197]
Create a products page (Blesh and Twocanoes initially) with short descriptions and images, linked from README.md

**Comment by leybzon** [comment]
I think this page will be very helpful. I can create one and list all products that are available for sale with links to the stores where people can buy them.

**Comment by schilit** [comment]
Sounds good. Send me a pull request.

**Comment by leybzon** [comment]
Please see the pull request:
https://github.com/google/uribeacon/pull/246

**Comment by leybzon** [comment]
Please suggest if anything else needs to be done with the pull request.

Thank you!

- Gene

**Comment by schilit** [comment]
Closing this as the #246 is merged. Let me know if anything is left unresolved and I can re-open.
