### ISSUE TITLE
Stuck reading beacon state

### ISSUE THREAD

**Issue by triblondon** [google/uribeacon#212]
I bought some beacons from Blesh to have a play with URIBeacons.  I have two problems:
1. Using either the Blesh app, or the Phyweb app (both on iOS) I get stuck on the 'reading' step of configuring the beacon.  I get to the 'press the config button' step, I press the config button on the beacon, the phone recognises that immedaitely, but then puts up a 'Reading' or 'Tap to cancel' message which never goes away.  I did manage to get this to work initially, so I'm perplexed about why this is now consistently failing in the same way.
2. Neither the Blesh nor Phyweb apps are available in Google play from my Nexus 7.  I searched the web using chrome for 'google play physical web' and then tapped the top result.  I was prompted to open in the Google play native app, said yes, and then got "No results found for "pub:The Physical Web Team".  I think that's because you've designated it as only available for phones (and I think a similar issue for the Blesh app)

**Comment by triblondon** [comment]
Interestingly I managed to resolve it by powering down all my beacons, restarting my iphone, launching the phyweb app, then powering up a single beacon.

**Comment by scottjenson** [comment]
There is an issue when you have large numbers of BLE devices that configuration is a problem. By powering them all down you clearly solved in. HOwever, having 3-5 shouldn't be an issue at all (I have 20 around me now) What might be useful to is install a generic BLE scanner (like Nordic nRF Master) and see if you are in a BLE rich zone ;-)

Scott
