### ISSUE TITLE
Clarification on URL length

### ISSUE THREAD

**Issue by paulirish** [google/uribeacon#224]
Wasn't totally clear how long the URLs could be but Jake spelled it out very clearly:

> Let's say we have a URL of the form "https://www.<X>.com". "https://www." is encoded in the scheme prefix. ".com" is encoded within the URL field but as a single byte. This leaves 16 bytes for <X>, which amounts to 16 characters in almost all cases.

Would love to see that added somewhere here, maybe in this section: https://github.com/google/uribeacon#short-urls

**Comment by scottjenson** [comment]
merged #236
