### ISSUE TITLE
Protocol specification

### ISSUE THREAD

**Issue by t-line** [google/uribeacon#247]
Hi all,
we are making our implementation of uriBeacon on both Nordic nrf51822 and  nrf51442 (in order to integrate even some ANT+ Service).

To better know the story of Uribeacon and try our solution, i'd like to check the protocol v1: is there any specification available?

Regards
M

**Comment by scottjenson** [comment]
The specification is here:
https://github.com/google/uribeacon/tree/master/specification

We also have a validator application in the releases section that can test compliance with the V2 specification. You specifically asking about 'v1' is a bit confusing (as we are on v2) however, the ad packet format between the 2 is identical so you should be fine. The primary difference between the two specs is the configuration service.

**Comment by t-line** [comment]
Scott,
I was just wondering how the adv packet in v1 was configured so to better understand some source related to nrf51. does this spec exists?

M

**Comment by scottjenson** [comment]
??? I linked to it in my previous comment. The Ad Packet for V1 and V2 are exactly the same

**Comment by t-line** [comment]
Sorry for my english, i'm looking for the spec of the configuration service GATT characteristics).

M

**Comment by scottjenson** [comment]
There was no configuration for the GATT services for V1, that was only added in V2

**Comment by t-line** [comment]
in V1 i see:
URI_UUID_BEACON_DATA_1_CHAR   0x7da7
URI_UUID_BEACON_DATA_2_CHAR    0x7da8
URI_UUID_BEACON_DATA_SIZE_CHAR     0x7da9

how are used?

If is not important to be compatible to V1, we wil start with V2 development right now

M

**Comment by scottjenson** [comment]
What I'm trying to tell you is that the ad packet is the ONLY critical piece. They are the same in V1 and V2. The only thing added in the V2 spec is a configuration service. The link provided above shows in detail what should be in the ad packet. Here is the ad packet portion of the spec. Just do this:
https://github.com/google/uribeacon/blob/master/specification/AdvertisingMode.md

**Comment by t-line** [comment]
Ok, thanks
