### ISSUE TITLE
Official Android app for configuration

### ISSUE THREAD

**Issue by t-line** [google/uribeacon#249]
Hi all,
sorry for this "stupid" question but i tried thousand times before write.
I can't find a way to configure all the uribeacon parameters with the official app, only the URI is configurable. Al lthe others parameter like period?

Thanks

M

**Comment by nissimzur** [comment]
I believe it still have many bugs. 
Call my Skype nissim.test and let share knowledge. 
-Nissim

**Comment by t-line** [comment]
Sorry i can't now...

**Comment by g-ortuno** [comment]
https://github.com/google/uribeacon

On Fri, Jun 26, 2015, 3:54 AM t-line <notifications@github.com> wrote:

> Sorry i can't now...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/uribeacon/issues/249#issuecomment-115645104>.
>
-- 
Gio

**Comment by scottjenson** [comment]
In the releases section, there is a URIBeacon app that will allow you to change not only the URI but also the transmit power and transmit frequency.

**Comment by valterforesto** [comment]
@scottjenson @g-ortuno 
Please answer questions always in a comprehensive way, this habit helps create a community rather than an elite. So please publish explicitly the URL of the APK that people can use to configure theirs uriBeacon. Thanks.

**Comment by scottjenson** [comment]
Sorry, I thought it was pretty clear, we've left the same message for others with problem. However, I'm happy to give you further details. Go to:

https://github.com/google/uribeacon/releases

and download:

uribeacon-sample-debug.apk
