### ISSUE TITLE
Advice for habit helps create a community rather than an elite

### ISSUE THREAD

**Issue by valterforesto** [google/uribeacon#250]
Please answer questions and explain ideas always in a comprehensive way, this habit helps create a community rather than an elite.
To build an international community that knows, appreciates and contribute to the development of Physical Web, try to empathize with those who make when you answer the questions answered in a way understandable to those who is not American and did not work in Google. 
Thanks in advance to other contributors.

**Comment by scottjenson** [comment]
Thank you for your advice, we will always strive to that.
